apiVersion: v1
kind: Service
metadata:
  name: flux-prod-service
  namespace: prod
spec:
  selector:
    app: flux-prod
  type: NodePort
  ports:
    - name: my-flux-prod-port
      nodePort: 32457
      port: 8084
      targetPort: 80