apiVersion: v1
kind: Service
metadata:
  name: flux-stage-service
  namespace: stage
spec:
  selector:
    app: flux-stage
  type: NodePort
  ports:
    - name: my-flux-stage-port
      nodePort: 32456
      port: 8082
      targetPort: 80