---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-stage
  namespace: stage
  labels:
    app: flux-stage
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.flux-stage: glob:stage-*
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flux-stage
  template:
    metadata:
      labels:
        app: flux-stage
    spec:
      containers:
      - name: flux-stage
        image: aashishgoyal246/test-flux:stage-692f0ec
        ports:
        - containerPort: 80
